In [1]:
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt
import cv2
from PIL import Image
from keras.preprocessing.image import array_to_img, img_to_array, load_img
import os
tf.__version__

Using TensorFlow backend.


'1.12.0'

In [2]:
from glob import glob

In [3]:
from os import walk
from os import listdir
from os.path import isfile, join

In [4]:
img = load_img('asl-alphabet/asl_alphabet_test/A_test.jpg')
def read_image(file_path):
    # For image visualization
    im = np.array(Image.open(file_path))
    img = cv2.imread(file_path, cv2.IMREAD_COLOR) #cv2.IMREAD_GRAYSCALE
    return img

def plot_pic(img):
    # Plot openCV pic
    pic = read_image(img)    
    plt.figure(figsize=(5,5))
    plt.imshow(pic)
    plt.show()

In [5]:
mypath='asl-alphabet/asl_alphabet_train'
train_imgs = []
for path, subdirs, files in os.walk(mypath):
    for file in files:
        img = read_image(os.path.join(path,file)).flatten()
        train_imgs.append(img)
print(len(train_imgs))

87003


In [6]:
train_imgs

[array([252,   0,   0, ..., 182,  14,   3], dtype=uint8),
 array([254,   2,   0, ..., 181,  13,   2], dtype=uint8),
 array([249,   1,   0, ..., 184,  10,   4], dtype=uint8),
 array([251,   2,   0, ..., 185,  12,   2], dtype=uint8),
 array([255,   3,   0, ..., 189,  11,   6], dtype=uint8),
 array([254,   6,   0, ..., 179,  14,   5], dtype=uint8),
 array([253,   4,   0, ..., 181,  11,   7], dtype=uint8),
 array([253,   3,   0, ..., 180,   8,  10], dtype=uint8),
 array([253,   4,   0, ..., 181,   8,   6], dtype=uint8),
 array([251,   2,   0, ..., 186,  13,   5], dtype=uint8),
 array([252,   1,   0, ..., 184,  11,   3], dtype=uint8),
 array([252,   1,   0, ..., 185,  13,   1], dtype=uint8),
 array([254,   4,   0, ..., 185,  10,   7], dtype=uint8),
 array([254,   0,   0, ..., 184,  12,   0], dtype=uint8),
 array([251,   3,   0, ..., 188,  14,   2], dtype=uint8),
 array([253,   1,   0, ..., 184,  13,   5], dtype=uint8),
 array([247,   5,   0, ..., 183,  13,   1], dtype=uint8),
 array([248,  